# Generated by Django 2.2.6 on 2019-10-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191020_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
